import { useEffect, useState } from 'react'
import type { AIAnalysis } from '../types'
import { api } from '../api/client'

const CATEGORY_LABEL: Record<string, string> = {
  compile_error: 'Compile error',
  test_failure: 'Test failure',
  dependency_error: 'Dependency error',
  timeout: 'Timeout',
  infra_error: 'Infrastructure error',
  configuration_error: 'Configuration error',
  flaky_test: 'Flaky test',
  unknown: 'Unknown',
}

export function AIAnalysisPanel({ attemptId, canAnalyze }: { attemptId: string; canAnalyze: boolean }) {
  const [analysis, setAnalysis] = useState<AIAnalysis | null | undefined>(undefined)
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    setAnalysis(undefined)
    api.getAnalysis(attemptId).then(setAnalysis)
  }, [attemptId])

  async function runAnalysis() {
    setLoading(true)
    try {
      const result = await api.triggerAnalysis(attemptId)
      setAnalysis(result)
    } catch (e: any) {
      setAnalysis({
        status: 'unavailable',
        provider: null, model: null, failure_category: null,
        root_cause: null, explanation: null, suggested_fix: null,
        confidence: null, error_message: String(e), created_at: new Date().toISOString(),
        completed_at: null,
      })
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="ai-panel">
      <div className="ai-panel-header">
        <span className="ai-panel-eyebrow">AI FAILURE ANALYZER</span>
        <span className="ai-panel-caveat">suggestion, not verified truth</span>
      </div>

      {analysis === undefined && <div className="ai-panel-empty">loading analysis…</div>}

      {analysis === null && canAnalyze && (
        <div className="ai-panel-empty">
          <p>No analysis yet for this attempt.</p>
          <button className="btn btn--ghost" onClick={runAnalysis} disabled={loading}>
            {loading ? 'analyzing…' : 'Run AI analysis'}
          </button>
        </div>
      )}

      {analysis === null && !canAnalyze && (
        <div className="ai-panel-empty">Analysis is only available for failed attempts.</div>
      )}

      {analysis && analysis.status === 'completed' && (
        <div className="ai-panel-body">
          <div className="ai-field">
            <span className="ai-field-label">category</span>
            <span className="pill">{CATEGORY_LABEL[analysis.failure_category ?? 'unknown']}</span>
          </div>
          <div className="ai-field">
            <span className="ai-field-label">confidence</span>
            <ConfidenceBar value={analysis.confidence ?? 0} />
          </div>
          <div className="ai-field ai-field--block">
            <span className="ai-field-label">likely root cause</span>
            <p>{analysis.root_cause}</p>
          </div>
          <div className="ai-field ai-field--block">
            <span className="ai-field-label">explanation</span>
            <p>{analysis.explanation}</p>
          </div>
          <div className="ai-field ai-field--block ai-field--fix">
            <span className="ai-field-label">suggested fix</span>
            <p>{analysis.suggested_fix}</p>
          </div>
          <p className="ai-disclaimer">
            Generated by {analysis.provider} ({analysis.model}). This is a suggestion for a human
            to evaluate — it may be wrong, and it never modifies code automatically.
          </p>
        </div>
      )}

      {analysis && analysis.status === 'invalid' && (
        <div className="ai-panel-warning">
          The model's response didn't match the expected format, so it was discarded rather than
          shown. This does not affect the job's pass/fail result.
        </div>
      )}

      {analysis && analysis.status === 'unavailable' && (
        <div className="ai-panel-warning">
          AI analysis is currently unavailable ({analysis.error_message ?? 'provider error'}). CI
          results are independent of AI availability.
        </div>
      )}
    </div>
  )
}

function ConfidenceBar({ value }: { value: number }) {
  const pct = Math.round(value * 100)
  return (
    <div className="confidence-bar" title={`${pct}% confidence`}>
      <div className="confidence-bar-fill" style={{ width: `${pct}%` }} />
      <span className="confidence-bar-label">{pct}%</span>
    </div>
  )
}
